### ISSUE TITLE
How to simple rename?

### ISSUE THREAD

**Issue by davidhealey** [SamWindell/AudioUtils#12]
Hi Sam,

How do I rename a folder of files to the detected midi note? This is what I tried but I get the error "A subcommand is required"

`signet folder rename <detected-midi-note>`

**Comment by polypx** [comment]
Hi David

Sam may have some better suggestions, but in the meantime, I’ve found that this works.

From the directory above your folder of samples.
signet folder-name rename suffix "<detected-midi-note>"

cheers
Dan

**Comment by SamWindell** [comment]
Cheers Dan. Yeah, suffix is probably your best bet. The other available options are: 
[prefix](https://github.com/SamWindell/Signet/blob/master/docs/usage.md#prefix)
[suffix](https://github.com/SamWindell/Signet/blob/master/docs/usage.md#suffix)
[regex-replace](https://github.com/SamWindell/Signet/blob/master/docs/usage.md#regex-replace)
[note-to-midi](https://github.com/SamWindell/Signet/blob/master/docs/usage.md#note-to-midi)
[auto-map](https://github.com/SamWindell/Signet/blob/master/docs/usage.md#auto-map)

You could use regex-replace like this too: `signet folder-name rename regex-replace ".*" "new-name-<detected-midi-note>"`
