### ISSUE TITLE
Rate conversion does not work with 27778 Hz old rompler WAV files

### ISSUE THREAD

**Issue by RoiDeLaPlage** [SamWindell/AudioUtils#17]
Hello,
I'm trying to convert many WAVs from old musical Romplers (format is : 27,778Hz, 1CH, 434 kbps) to standard 44.1Khz, 16 bits but the program does not make the conversion.

Example : signet.exe 12_Strings_Guitar_EII_hfe_S1.wav -convert sample-rate 44100 bit-depth 16

The returned error is :
ERROR:
Input files: The input part sample-rate is neither a file, directory, or pattern
Run with --help or --help-all for more information.

This is converted correctly using FormatFactory but I'm losing the looping points.
Any quick workaround ?
Thanks !
Fred

**Comment by SamWindell** [comment]
Hi, I've never tried non-standard sample-rates but it might work.
I think I see an error with your command though, you have `-` in from of the word convert. The commands in signet don't have any dashes. So it should be: `signet.exe 12_Strings_Guitar_EII_hfe_S1.wav convert sample-rate 44100 bit-depth 16`

**Comment by RoiDeLaPlage** [comment]
Thanks for your quick feedback.
Indeed, I mistyped the command line, should have copy/pasted it !

I confirm the non-standard WAV sample-rate of 27778Hz is not working properly with Signet.
I made a test, converting 27.8Khz to "low quality" 22050Hz (2CH) using FormatFactory.
Then tried the rate conversion to 44.1kHz with both 27.8kHz and 22kHz files in the directory : Signet only converted the 22kHz see below 

[Signet]: Searching for files non-recursively in the directory .
[Signet]: Use the option --recursive to search in all subdirecties of the given one as well.
[Signet]: Found 6 matching files
[Convert]: Starting processing
[Signet]: Reading file: 12_String_Guitar_EII_hfe_S1 [Low quality]
[Signet]: Reading file: 12_String_Guitar_EII_hfe_S2 [Low quality]
[Signet]: Reading file: 12_String_Guitar_EII_hfe_S3 [Low quality]
[Signet]: Reading file: 12_String_Guitar_EII_hfe_S4 [Low quality]
[Signet]: Reading file: 12_String_Guitar_EII_hfe_S5 [Low quality]
[Signet]: Reading file: 12_String_Guitar_EII_hfe_S6 [Low quality]
[Convert]: Seting the bit rate from 16 to 16: 12_String_Guitar_EII_hfe_S1 [Low quality]
[Convert]: Converting sample rate from 22050 to 44100: 12_String_Guitar_EII_hfe_S1 [Low quality]
[Convert]: Seting the bit rate from 16 to 16: 12_String_Guitar_EII_hfe_S2 [Low quality]
[Convert]: Converting sample rate from 22050 to 44100: 12_String_Guitar_EII_hfe_S2 [Low quality]
[Convert]: Seting the bit rate from 16 to 16: 12_String_Guitar_EII_hfe_S3 [Low quality]
[Convert]: Converting sample rate from 22050 to 44100: 12_String_Guitar_EII_hfe_S3 [Low quality]
[Convert]: Seting the bit rate from 16 to 16: 12_String_Guitar_EII_hfe_S4 [Low quality]
[Convert]: Converting sample rate from 22050 to 44100: 12_String_Guitar_EII_hfe_S4 [Low quality]
[Convert]: Seting the bit rate from 16 to 16: 12_String_Guitar_EII_hfe_S5 [Low quality]
[Convert]: Converting sample rate from 22050 to 44100: 12_String_Guitar_EII_hfe_S5 [Low quality]
[Convert]: Seting the bit rate from 16 to 16: 12_String_Guitar_EII_hfe_S6 [Low quality]
[Convert]: Converting sample rate from 22050 to 44100: 12_String_Guitar_EII_hfe_S6 [Low quality]
[Convert]: Total audio files edited: 6
[Convert]: Total audio file paths edited: 0
[Signet]: Clearing the old backup data ready for new changes to be saved
[Signet]: Overwriting file: 12_String_Guitar_EII_hfe_S1 [Low quality]
[Signet]: Overwriting file: 12_String_Guitar_EII_hfe_S2 [Low quality]
[Signet]: Overwriting file: 12_String_Guitar_EII_hfe_S3 [Low quality]
[Signet]: Overwriting file: 12_String_Guitar_EII_hfe_S4 [Low quality]
[Signet]: Overwriting file: 12_String_Guitar_EII_hfe_S5 [Low quality]
[Signet]: Overwriting file: 12_String_Guitar_EII_hfe_S6 [Low quality]
Signet completed successfully.

where the directory holds 12 files.

Fred

PS: typo with "SetTing the bit rate from..."

**Comment by SamWindell** [comment]
Ok thank you, could be a bug here, I'll take a closer look when I have a minute. 

Good spot with the typo - I've fixed that now.

**Comment by RoiDeLaPlage** [comment]
I can send you sample files for testing if it makes sense.
Checked SOX : it does make the 27.8 to 44 conversion but doesn't keep the looping information :(

Fred

**Comment by SamWindell** [comment]
Yes actually that would be helpful thanks. Just one file would do. You can either attach it here or send me an email if you prefer: info@frozenplain.com

**Comment by SamWindell** [comment]
We concluded #18 is the cause of this problem rather than sample-rate conversion
