### ISSUE TITLE
dr_wav.h

### ISSUE THREAD

**Issue by aleksia123** [SamWindell/AudioUtils#3]
Hey, very nice audio program, i used the binaries but it caused some troubles with dr_wav.h 

I saw you recently made changes to dr_.wav.h, I compiled it but the problem still persists.

I compiled it with WSL on windows. 

When I use "signet Samples tune 4800", so the "tune" algorithm, it gives me the following output:

signet: /mnt/c/temp/cppcode/Signet/code/third_party_libs/dr_wav.h:3050: drwav_bool32 drwav_init__internal(drwav*, drwav_chunk_proc, void*, drwav_uint32): Assertion `bytesRead <= header.sizeInBytes' failed.
Aborted (core dumped)

Is this maybe windows related? I didn't cross compile it.
And maybe can you provide the latest binaries, thanks for your efforts.

**Comment by SamWindell** [comment]
Ah yes looks like you bumped into a bug with the WAV writer (but it would be caught by the loader).

I've bumped the version number if for if you or others want the binaries.
