### ISSUE TITLE
Missing dll's (Debug dll's?) 

### ISSUE THREAD

**Issue by NS-Viktor** [SamWindell/AudioUtils#4]
Hi! When trying to run the released binaries I seem to be missing dll's, for example VCRUNTIME140_1D.dll. The "D" at the end seems to be the culprit, indicating Debug dll's, if I understand it correctly. (?) I've made sure to install the latest Visual Studio redistributables, both 32 and 64 bit, but to no avail. Any help is greatly appreciated! Thanks!! /Viktor Lindholm

**Comment by SamWindell** [comment]
Hey Victor, thanks for the details. I can change a build setting that I believe will fix this issue - I'll get that added and push a new version when I have some time!

**Comment by SamWindell** [comment]
Just pushed a new version, 0.1.3, with a fix for this.

Feel free to comment back here if the issue still persists in the new version!
